name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./turing-arena-frontend

      - name: Build the project
        run: npm run build
        working-directory: ./turing-arena-frontend

      - name: Configure git
        run: |
          git config --global user.email "sethupavan12@gmail.com"
          git config --global user.name "Sethu"
        working-directory: ./turing-arena-frontend

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
        working-directory: ./turing-arena-frontend
